# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
---
facets:
  employee_address_type:
    EmailEmployee:
      title: "Email"
      scope: "EMAIL"
    PhoneEmployee:
      title: "Telefon"
      scope: "PHONE"
    MobilePhoneEmployee:
      title: "Mobiltelefon"
      scope: "PHONE"
    InstitutionPhoneEmployee:
      title: "Institutionstelefonnummer"
      scope: "PHONE"
  visibility:
    Public:
      title: "Må vises eksternt"
      scope: "PUBLIC"
    Secret:
      title: "Hemmelig"
      scope: "SECRET"
  engagement_job_function:
    not_applicable:
      title: "N/A"
      scope: "TEXT"
  engagement_type:
    omada_manually_created:
      title: "(Omada) Manuelt oprettet"
      scope: "TEXT"
    omada_manually_created_hidden:
      title: "(Omada) Manuelt oprettet (Skjult)"
      scope: "TEXT"
  primary_type:
    primary:
      title: "Primær"
      scope: "3000"

it_systems:
  omada_ad_guid: "Omada - AD GUID"
  omada_ad_login: "Omada - AD LOGIN"
  omada_login: "Omada - LOGIN"
